# Generated by Django 4.1.1 on 2022-10-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temp_kelvin", models.FloatField()),
                ("temp_celcius", models.FloatField()),
                ("temp_fahrenheit", models.FloatField()),
                ("date", models.DateTimeField()),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
